# Generated by Django 3.0.8 on 2020-10-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sreet_address2',
            new_name='street_address2',
        ),
    ]
